# Generated by Django 3.1.1 on 2020-10-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-date',)},
        ),
    ]
